version: "3.8"

services:
  nest:
    container_name: nest
    build:
      context: ./project
    volumes:
      - ./project:/app
      - /app/node_modules
    ports:
      - 3000:3000

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  adminer:
    container_name: adminer
    image: adminer
    environment:
        ADMINER_DESIGN: pepa-linha-dark
    ports:
      - "8080:8080"
volumes:
  data:
